[package]
name = "single-price-feed"
version = "0.1.0"
edition = "2024"
# rust-version = ""

[dependencies]
anyhow = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
seda-sdk-rs = "1.0"
ethabi = "18.0"
