[package]
name = "xtask"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
convert_case = "0.8"
dotenvy = "0.15"
inquire = { version = "0.7", default-features = false, features = [
	"crossterm",
] }
xshell = "0.2"
