[package]
name = "caplight-eod-market-price"
version = "0.1.0"
edition = "2024"
# rust-version = ""

[features]
default = ["testnet"]
testnet = []
mainnet = []

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
seda-sdk-rs = "1.0"
ethabi = "18.0"
